# Generated by Django 6.0.5 on 2026-05-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Your Message')),
                ('is_read', models.BooleanField(default=False, help_text='Admin has read this message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
