# Generated by Django 6.0.6 on 2026-06-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('ai', 'Artificial Intelligence'), ('automation', 'Automation'), ('vision', 'Computer Vision'), ('data', 'Data Intelligence'), ('chatbot', 'Chatbot'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
