# Generated by Django 6.0.6 on 2026-06-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('ai', 'AI Automation'), ('data', 'Data Intelligence'), ('vision', 'Computer Vision')], db_index=True, max_length=20)),
                ('icon', models.CharField(help_text='Emoji for the project', max_length=10)),
                ('description', models.TextField()),
                ('results', models.TextField(help_text='Results achieved with this project')),
                ('tech', models.JSONField(default=list, help_text='List of technologies used')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'portfolio_projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
